export const LOGIN_USER_NAME  = 'LOGIN_USER_NAME';
export const LOGIN_USER_PASSWORD = 'LOGIN_USER_PASSWORD';
export const LOGIN_USER_AGE = 'LOGIN_USER_AGE';
export const FETCH_USERS_DATA = 'FETCH_USERS_DATA';